// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure.Persistence;

#nullable disable

namespace UrlShortener.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Domain.Entities.AdminLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_entity");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_logs");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_logs_created_at");

                    b.HasIndex("TargetEntity", "TargetId")
                        .HasDatabaseName("ix_admin_logs_target_entity_target_id");

                    b.ToTable("admin_logs", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("AiEstimatedReadingMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("ai_estimated_reading_minutes");

                    b.Property<string>("AiKeyTopics")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ai_key_topics");

                    b.Property<string>("AiKeywords")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ai_keywords");

                    b.Property<string>("AiSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ai_summary");

                    b.Property<bool>("AiSummaryAttempted")
                        .HasColumnType("boolean")
                        .HasColumnName("ai_summary_attempted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCustomAlias")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom_alias");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_url");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("short_code");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("VtCheckAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vt_check_attempts");

                    b.Property<DateTimeOffset?>("VtCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vt_checked_at");

                    b.Property<string>("VtStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vt_status");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_links_short_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_links_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("VtStatus")
                        .HasDatabaseName("ix_links_vt_status")
                        .HasFilter("vt_status IN ('Pending', 'Malicious', 'Unresolved')");

                    b.ToTable("links", null, t =>
                        {
                            t.HasCheckConstraint("chk_short_code_format", "short_code ~ '^[A-Za-z0-9_-]+$'");
                        });
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.LinkClick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Browser")
                        .HasColumnType("text")
                        .HasColumnName("browser");

                    b.Property<DateTimeOffset>("ClickedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<string>("Referrer")
                        .HasColumnType("text")
                        .HasColumnName("referrer");

                    b.HasKey("Id")
                        .HasName("pk_link_clicks");

                    b.HasIndex("LinkId", "ClickedAt")
                        .HasDatabaseName("ix_link_clicks_link_id_clicked_at");

                    b.ToTable("link_clicks", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.LinkClickDailyStat", b =>
                {
                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer")
                        .HasColumnName("click_count");

                    b.Property<string>("DeviceBreakdownJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("device_breakdown");

                    b.Property<string>("TopCountry")
                        .HasColumnType("text")
                        .HasColumnName("top_country");

                    b.Property<string>("TopReferrer")
                        .HasColumnType("text")
                        .HasColumnName("top_referrer");

                    b.HasKey("LinkId", "StatDate")
                        .HasName("pk_link_click_daily_stats");

                    b.HasIndex("LinkId", "StatDate")
                        .HasDatabaseName("ix_link_click_daily_stats_link_id_stat_date");

                    b.ToTable("link_click_daily_stats", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.PayOsOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("AmountVnd")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_vnd");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payos_orders");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ix_payos_orders_order_code");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payos_orders_user_id");

                    b.ToTable("payos_orders", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_reports_link_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reports_status")
                        .HasFilter("status = 'Pending'");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("PaymentProviderRef")
                        .HasColumnType("text")
                        .HasColumnName("payment_provider_ref");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscriptions_status")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role")
                        .HasFilter("role = 'Admin'");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_verification_codes");

                    b.HasIndex("UserId", "Type")
                        .HasDatabaseName("ix_verification_codes_user_id_type");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Link", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_links_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.LinkClickDailyStat", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.Link", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_click_daily_stats_links_link_id");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.PayOsOrder", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payos_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Report", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.Link", "Link")
                        .WithMany("Reports")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_links_link_id");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.VerificationCode", b =>
                {
                    b.HasOne("UrlShortener.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.Link", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("UrlShortener.Domain.Entities.User", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
