<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UrlShortener.Worker-383dc15c-d893-4b31-8f23-a410a3cfff10</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrlShorterner.Application\UrlShortener.Application.csproj" />
    <ProjectReference Include="..\UrlShorterner.Infrastructure\UrlShortener.Infrastructure.csproj" />
  </ItemGroup>
</Project>
