<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrlShortener.Contracts\UrlShortener.Contracts.csproj" />
    <ProjectReference Include="..\UrlShorterner.Domain\UrlShortener.Domain.csproj" />
  </ItemGroup>

</Project>
