<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1f5bb3e6-571c-4a15-8524-6447529973e5</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UrlShorterner.Application\UrlShortener.Application.csproj" />
    <ProjectReference Include="..\UrlShorterner.Domain\UrlShortener.Domain.csproj" />
    <ProjectReference Include="..\UrlShorterner.Infrastructure\UrlShortener.Infrastructure.csproj" />
    <ProjectReference Include="..\UrlShorterner.ServiceDefaults\UrlShortener.ServiceDefaults.csproj" />
    <ProjectReference Include="..\UrlShorterner\UrlShortener.csproj" />
  </ItemGroup>

</Project>
